sudo: false
dist: xenial
language: ruby
rvm:
- 2.4.3
if: branch = main OR repo =~ /-internal/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- if [[ -z "$DEPLOY_BRANCH" ]]; then export DEPLOY_BRANCH=gh-pages; fi
- cp -rl dependencies/jekyll/search.html ./concepts/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ concepts\/search\.html/g' ./concepts/search.html
- cp -rl dependencies/jekyll/search.html ./get-started/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ get-started\/search\.html/g' ./get-started/search.html
- cp -rl dependencies/jekyll/search.html ./overview/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ overview\/search\.html/g' ./overview/search.html
- cp -rl dependencies/jekyll/search.html ./release-notes/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ release-notes\/search\.html/g' ./release-notes/search.html
- cp -rl dependencies/jekyll/search.html ./rest-api/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ rest-api\/search\.html/g' ./rest-api/search.html
- cp -rl dependencies/jekyll/search.html ./solutions/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ solutions\/search\.html/g' ./solutions/search.html
- cp -rl dependencies/jekyll/search.html ./support/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ support\/search\.html/g' ./support/search.html
- cp -rl dependencies/jekyll/search.html ./use/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ use\/search\.html/g' ./use/search.html
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
- sudo apt-get -y install graphicsmagick graphicsmagick-libmagick-dev-compat libmagickwand-dev
install: bundle install --quiet --jobs=3 --retry=3
script:
- if [[ ! -z "$FEATURE_FLAG" ]]; then bundle exec rake buildAll; fi
- mkdir -p /tmp/output && bundle exec jekyll build --trace --destination /tmp/output --config _config.yml,project.yml
- touch /tmp/output/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  local_dir: /tmp/output
  target_branch: $DEPLOY_BRANCH
  verbose: true
  on:
    all_branches: true
