sidebar:
  entries:
    - title: Astra Enterprise docs
      url: /index.html
    - section: overview
    - section: release-notes
    - section: concepts
    - section: get-started
    - section: setup
    - section: use
    - section: solutions
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started with Astra Service
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Service
          url: https://docs.netapp.com/us-en/get-started/intro.html
        - title: What's new with Astra Service
          url: https://docs.netapp.com/us-en/release-notes/whats-new.html
        - title: Try it out
        - title: Get started with Astra Service & Google Cloud
        - title: Get started with Astra Service & Microsoft Azure
    - title: Use Astra Service
      links:
        - title: Manage accounts
        - title: Manage apps
          url: https://docs.netapp.com/us-en/use/manage-apps.html
        - title: Protect apps
          url: https://docs.netapp.com/us-en/use/protect-apps.html
        - title: Migrate apps
          url: https://docs.netapp.com/us-en/use/clone-apps.html
        - title: Set up billing
          url: https://docs.netapp.com/us-en/use/set-up-billing.html
    - title: Use Astra Service <unique thing>
      links:
        - title: Do something in Astra Service
        - title: Do something in Astra Service
    - title: Get started with Astra Enterprise
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Enterprise
          url: /overview/intro.html
        - title: What's new with Astra Enterprise
          url: /release-notes/whats-new.html
        - title: Try it out
        - title: Download and install Astra Enterprise
    - title: Use Astra Enterprise
      links:
        - title: Manage accounts
        - title: Manage apps
          url: /use/manage-apps.html
        - title: Protect apps
          url: /use/protect-apps.html
        - title: Migrate apps
          url: /use/clone-apps.html
    - title: Use Astra Entrprise in VMware
      links:
        - title: Get started using Astra Enterprise in VMware
        - title: Manage apps using VMware
        - title: Protect apps using VMware
        - title: Migrate apps using VMware
    - title: Use Astra API
      links:
        - title: Get started with the Astra API
        - title: API reference
    - title: Demos & tutorials
      links:
        - title: Astra Enterprise videos
          url: /get-started/videos.html
        - title: NetApp University Astra training (login required)
    - title: Blogs & community
      links:
        - title: Slack
          summary: Ask questions, exchange ideas, and share best practices.
          url: https://netapppub.slack.com/#astra
        - title: NetApp Community
        - title: Kubernetes Hub
          url: https://cloud.netapp.com/kubernetes-hub
        - title: Where to get help
